#!/usr/bin/env bash
set -e

CONTAINER_NAME=flask_tutorial_redis
docker run --rm -d --name=$CONTAINER_NAME -p 6379:6379 redis

# From now on, if the user presses Ctrl+C we should teardown
function cleanup() {
    docker stop $CONTAINER_NAME
}
trap cleanup INT
trap cleanup ERR

rqworker & flask run